//
//  CardGameModel.swift
//  aliasTeamApp
//
//  Created by BSergio on 23.02.2022.
//

import Foundation

struct CardGameModel {
    let cardWord: String
    let categoryName: String
    let point: Int
    
    static func getCardsGame(with category: String) -> [CardGameModel] {
        return [
            CardGameModel(cardWord: "деревья", categoryName: "Nature" , point: 1),
            CardGameModel(cardWord: "лес", categoryName: "Nature" , point: 1),
            CardGameModel(cardWord: "трава", categoryName: "Nature" , point: 1),
            CardGameModel(cardWord: "воздух", categoryName: "Nature" , point: 1),
            CardGameModel(cardWord: "растения", categoryName: "Nature" , point: 1),
            CardGameModel(cardWord: "цветы", categoryName: "Nature" , point: 1),
            CardGameModel(cardWord: "озеро", categoryName: "Nature" , point: 1),
            CardGameModel(cardWord: "животные", categoryName: "Nature" , point: 1),
            CardGameModel(cardWord: "солнце", categoryName: "Nature" , point: 1),
            CardGameModel(cardWord: "отдых", categoryName: "Nature" , point: 1),
            CardGameModel(cardWord: "море", categoryName: "Nature" , point: 1),
            CardGameModel(cardWord: "река", categoryName: "Nature" , point: 1),
            CardGameModel(cardWord: "небо", categoryName: "Nature" , point: 1),
            CardGameModel(cardWord: "флора", categoryName: "Nature" , point: 1),
            CardGameModel(cardWord: "фауна", categoryName: "Nature" , point: 1),
            CardGameModel(cardWord: "птицы", categoryName: "Nature" , point: 1),
            CardGameModel(cardWord: "красота", categoryName: "Nature" , point: 1),
            CardGameModel(cardWord: "вода", categoryName: "Nature" , point: 1),
            CardGameModel(cardWord: "земля", categoryName: "Nature" , point: 1),
            CardGameModel(cardWord: "горы", categoryName: "Nature" , point: 1),
            CardGameModel(cardWord: "пикник", categoryName: "Nature" , point: 1),
            CardGameModel(cardWord: "зелень", categoryName: "Nature" , point: 1),
            CardGameModel(cardWord: "жизнь", categoryName: "Nature" , point: 1),
            CardGameModel(cardWord: "человек", categoryName: "Nature" , point: 1),
            CardGameModel(cardWord: "мир", categoryName: "Nature" , point: 1),
            CardGameModel(cardWord: "шашлык", categoryName: "Nature" , point: 1),
            CardGameModel(cardWord: "поле", categoryName: "Nature" , point: 1),
            CardGameModel(cardWord: "погода", categoryName: "Nature" , point: 1),
            CardGameModel(cardWord: "звери", categoryName: "Nature" , point: 1),
            CardGameModel(cardWord: "экология", categoryName: "Nature" , point: 1),
            CardGameModel(cardWord: "пейзаж", categoryName: "Nature" , point: 1),
            CardGameModel(cardWord: "биология", categoryName: "Nature" , point: 1),
            CardGameModel(cardWord: "грибы", categoryName: "Nature" , point: 1),
            CardGameModel(cardWord: "мать", categoryName: "Nature" , point: 1),
            CardGameModel(cardWord: "насекомые", categoryName: "Nature" , point: 1),
            CardGameModel(cardWord: "листья", categoryName: "Nature" , point: 1),
            CardGameModel(cardWord: "лето", categoryName: "Nature" , point: 1),
            CardGameModel(cardWord: "дача", categoryName: "Nature" , point: 1),
            CardGameModel(cardWord: "луг", categoryName: "Nature" , point: 1),
            CardGameModel(cardWord: "натура", categoryName: "Nature" , point: 1),
            CardGameModel(cardWord: "океан", categoryName: "Nature" , point: 1),
            CardGameModel(cardWord: "леса", categoryName: "Nature" , point: 1),
            CardGameModel(cardWord: "дождь", categoryName: "Nature" , point: 1),
            CardGameModel(cardWord: "люди", categoryName: "Nature" , point: 1),
            CardGameModel(cardWord: "ветер", categoryName: "Nature" , point: 1),
            CardGameModel(cardWord: "костёр", categoryName: "Nature" , point: 1),
            CardGameModel(cardWord: "красивая", categoryName: "Nature" , point: 1),
            CardGameModel(cardWord: "весна", categoryName: "Nature" , point: 1),
            CardGameModel(cardWord: "поляна", categoryName: "Nature" , point: 1),
            CardGameModel(cardWord: "зелёная", categoryName: "Nature" , point: 1),
            CardGameModel(cardWord: "рыбалка", categoryName: "Nature" , point: 1),
            CardGameModel(cardWord: "рыба", categoryName: "Nature" , point: 1),
            CardGameModel(cardWord: "счастье", categoryName: "Nature" , point: 1),
            CardGameModel(cardWord: "зима", categoryName: "Nature" , point: 1),
            CardGameModel(cardWord: "поля", categoryName: "Nature" , point: 1),
            CardGameModel(cardWord: "род", categoryName: "Nature" , point: 1),
            CardGameModel(cardWord: "берёза", categoryName: "Nature" , point: 1),
            CardGameModel(cardWord: "куст", categoryName: "Nature" , point: 1),
            CardGameModel(cardWord: "деревня", categoryName: "Nature" , point: 1),
            CardGameModel(cardWord: "речка", categoryName: "Nature" , point: 1),
            CardGameModel(cardWord: "кислород", categoryName: "Nature" , point: 1),
            CardGameModel(cardWord: "природный", categoryName: "Nature" , point: 1),
            CardGameModel(cardWord: "чистота", categoryName: "Nature" , point: 1),
            CardGameModel(cardWord: "комары", categoryName: "Nature" , point: 1),
            CardGameModel(cardWord: "родина", categoryName: "Nature" , point: 1),
            CardGameModel(cardWord: "медведь", categoryName: "Nature" , point: 1),
            CardGameModel(cardWord: "осень", categoryName: "Nature" , point: 1),
            CardGameModel(cardWord: "природоведение", categoryName: "Nature" , point: 1),
            CardGameModel(cardWord: "ягоды", categoryName: "Nature" , point: 1),
            CardGameModel(cardWord: "свежий воздух", categoryName: "Nature" , point: 1),
            CardGameModel(cardWord: "заповедник", categoryName: "Nature" , point: 1),
            CardGameModel(cardWord: "сад", categoryName: "Nature" , point: 1),
            CardGameModel(cardWord: "цветок", categoryName: "Nature" , point: 1),
            CardGameModel(cardWord: "планета", categoryName: "Nature" , point: 1),
            CardGameModel(cardWord: "песок", categoryName: "Nature" , point: 1),
            CardGameModel(cardWord: "пляж", categoryName: "Nature" , point: 1),
            CardGameModel(cardWord: "облака", categoryName: "Nature" , point: 1),
            CardGameModel(cardWord: "радость", categoryName: "Nature" , point: 1),
            CardGameModel(cardWord: "зоология", categoryName: "Nature" , point: 1),
            CardGameModel(cardWord: "поход", categoryName: "Nature" , point: 1),
            CardGameModel(cardWord: "парк", categoryName: "Nature" , point: 1),
            CardGameModel(cardWord: "животное", categoryName: "Nature" , point: 1),
            CardGameModel(cardWord: "роща", categoryName: "Nature" , point: 1),
            CardGameModel(cardWord: "закат", categoryName: "Nature" , point: 1),
            CardGameModel(cardWord: "улица", categoryName: "Nature" , point: 1),
            CardGameModel(cardWord: "ручей", categoryName: "Nature" , point: 1),
            CardGameModel(cardWord: "листва", categoryName: "Nature" , point: 1),
            CardGameModel(cardWord: "дуб", categoryName: "Nature" , point: 1),
            CardGameModel(cardWord: "снег", categoryName: "Nature" , point: 1),
            CardGameModel(cardWord: "день", categoryName: "Nature" , point: 1),
            CardGameModel(cardWord: "любовь", categoryName: "Nature" , point: 1),
            CardGameModel(cardWord: "бог", categoryName: "Nature" , point: 1),
            CardGameModel(cardWord: "луна", categoryName: "Nature" , point: 1),
            CardGameModel(cardWord: "охрана", categoryName: "Nature" , point: 1),
            CardGameModel(cardWord: "камень", categoryName: "Nature" , point: 1),
            CardGameModel(cardWord: "муравей", categoryName: "Nature" , point: 1),
            CardGameModel(cardWord: "сосна", categoryName: "Nature" , point: 1),
            CardGameModel(cardWord: "живая", categoryName: "Nature" , point: 1),
            CardGameModel(cardWord: "красиво", categoryName: "Nature" , point: 1),
            CardGameModel(cardWord: "палатка", categoryName: "Nature" , point: 1),
            CardGameModel(cardWord: "эколог", categoryName: "Nature" , point: 1),
            CardGameModel(cardWord: "явление", categoryName: "Nature" , point: 1),
            CardGameModel(cardWord: "красоты", categoryName: "Nature" , point: 1),
            CardGameModel(cardWord: "круговорот", categoryName: "Nature" , point: 1),
            CardGameModel(cardWord: "катаклизм", categoryName: "Nature" , point: 1),
            CardGameModel(cardWord: "красотища", categoryName: "Nature" , point: 1),
            CardGameModel(cardWord: "окружающее", categoryName: "Nature" , point: 1),
            CardGameModel(cardWord: "Эко", categoryName: "Nature" , point: 1),
            CardGameModel(cardWord: "долина", categoryName: "Nature" , point: 1),
            CardGameModel(cardWord: "палатки", categoryName: "Nature" , point: 1),
            CardGameModel(cardWord: "ресурс", categoryName: "Nature" , point: 1),
            CardGameModel(cardWord: "вылазка", categoryName: "Nature" , point: 1),
            CardGameModel(cardWord: "шалаш", categoryName: "Nature" , point: 1),
            CardGameModel(cardWord: "красота спасёт мир", categoryName: "Nature" , point: 1),
            CardGameModel(cardWord: "шашлыки", categoryName: "Nature" , point: 1),
            CardGameModel(cardWord: "мангал", categoryName: "Nature" , point: 1),
            CardGameModel(cardWord: "шампур", categoryName: "Nature" , point: 1),
            CardGameModel(cardWord: "пансионат", categoryName: "Nature" , point: 1),
            CardGameModel(cardWord: "отбор", categoryName: "Nature" , point: 1),
            CardGameModel(cardWord: "простор", categoryName: "Nature" , point: 1),
            CardGameModel(cardWord: "уединение", categoryName: "Nature" , point: 1),
            CardGameModel(cardWord: "рельеф", categoryName: "Nature" , point: 1),
            CardGameModel(cardWord: "лесок", categoryName: "Nature" , point: 1),
            CardGameModel(cardWord: "сахалин", categoryName: "Nature" , point: 1),
            CardGameModel(cardWord: "лужок", categoryName: "Nature" , point: 1),
            CardGameModel(cardWord: "стихия", categoryName: "Nature" , point: 1),
            CardGameModel(cardWord: "выходной", categoryName: "Nature" , point: 1),
            CardGameModel(cardWord: "ареал", categoryName: "Nature" , point: 1),
            CardGameModel(cardWord: "пуща", categoryName: "Nature" , point: 1),
            CardGameModel(cardWord: "ресурсы", categoryName: "Nature" , point: 1),
            CardGameModel(cardWord: "загород", categoryName: "Nature" , point: 1),
            CardGameModel(cardWord: "холм", categoryName: "Nature" , point: 1),
            CardGameModel(cardWord: "костерок", categoryName: "Nature" , point: 1),
            CardGameModel(cardWord: "панорама", categoryName: "Nature" , point: 1),
            CardGameModel(cardWord: "минералы", categoryName: "Nature" , point: 1),
            CardGameModel(cardWord: "дикие животные", categoryName: "Nature" , point: 1),
            CardGameModel(cardWord: "гамак", categoryName: "Nature" , point: 1),
            CardGameModel(cardWord: "торнадо", categoryName: "Nature" , point: 1),
            CardGameModel(cardWord: "богомол", categoryName: "Nature" , point: 1),
            CardGameModel(cardWord: "смерч", categoryName: "Nature" , point: 1),
            CardGameModel(cardWord: "дикий", categoryName: "Nature" , point: 1),
            CardGameModel(cardWord: "цветение", categoryName: "Nature" , point: 1),
            CardGameModel(cardWord: "гулянье", categoryName: "Nature" , point: 1),
            CardGameModel(cardWord: "растение", categoryName: "Nature" , point: 1),
            CardGameModel(cardWord: "цивилизация", categoryName: "Nature" , point: 1),
            CardGameModel(cardWord: "мошка", categoryName: "Nature" , point: 1),
            CardGameModel(cardWord: "потепление", categoryName: "Nature" , point: 1),
            CardGameModel(cardWord: "роса", categoryName: "Nature" , point: 1),
            CardGameModel(cardWord: "штатив", categoryName: "Nature" , point: 1),
            CardGameModel(cardWord: "прогулки", categoryName: "Nature" , point: 1),
            CardGameModel(cardWord: "аномалия", categoryName: "Nature" , point: 1),
            CardGameModel(cardWord: "окружение", categoryName: "Nature" , point: 1),
            CardGameModel(cardWord: "горизонт", categoryName: "Nature" , point: 1),
            CardGameModel(cardWord: "бизон", categoryName: "Nature" , point: 1),
            CardGameModel(cardWord: "испарение", categoryName: "Nature" , point: 1),
            CardGameModel(cardWord: "гриб", categoryName: "Nature" , point: 1),
            CardGameModel(cardWord: "дикобраз", categoryName: "Nature" , point: 1),
            CardGameModel(cardWord: "флористика", categoryName: "Nature" , point: 1),
            CardGameModel(cardWord: "гейзер", categoryName: "Nature" , point: 1),
            CardGameModel(cardWord: "аллея", categoryName: "Nature" , point: 1),

            CardGameModel(cardWord: "машина", categoryName: "Transport" , point: 1),
            CardGameModel(cardWord: "автобус", categoryName: "Transport" , point: 1),
            CardGameModel(cardWord: "трамвай", categoryName: "Transport" , point: 1),
            CardGameModel(cardWord: "троллейбус", categoryName: "Transport" , point: 1),
            CardGameModel(cardWord: "самолёт", categoryName: "Transport" , point: 1),
            CardGameModel(cardWord: "поезд", categoryName: "Transport" , point: 1),
            CardGameModel(cardWord: "дорога", categoryName: "Transport" , point: 1),
            CardGameModel(cardWord: "велосипед", categoryName: "Transport" , point: 1),
            CardGameModel(cardWord: "метро", categoryName: "Transport" , point: 1),
            CardGameModel(cardWord: "автомобиль", categoryName: "Transport" , point: 1),
            CardGameModel(cardWord: "водитель", categoryName: "Transport" , point: 1),
            CardGameModel(cardWord: "маршрутка", categoryName: "Transport" , point: 1),
            CardGameModel(cardWord: "такси", categoryName: "Transport" , point: 1),
            CardGameModel(cardWord: "колесо", categoryName: "Transport" , point: 1),
            CardGameModel(cardWord: "руль", categoryName: "Transport" , point: 1),
            CardGameModel(cardWord: "люди", categoryName: "Transport" , point: 1),
            CardGameModel(cardWord: "мотоцикл", categoryName: "Transport" , point: 1),
            CardGameModel(cardWord: "билет", categoryName: "Transport" , point: 1),
            CardGameModel(cardWord: "пассажир", categoryName: "Transport" , point: 1),
            CardGameModel(cardWord: "езда", categoryName: "Transport" , point: 1),
            CardGameModel(cardWord: "общественный", categoryName: "Transport" , point: 1),
            CardGameModel(cardWord: "ездить", categoryName: "Transport" , point: 1),
            CardGameModel(cardWord: "авто", categoryName: "Transport" , point: 1),
            CardGameModel(cardWord: "кондуктор", categoryName: "Transport" , point: 1),
            CardGameModel(cardWord: "электричка", categoryName: "Transport" , point: 1),
            CardGameModel(cardWord: "корабль", categoryName: "Transport" , point: 1),
            CardGameModel(cardWord: "вертолёт", categoryName: "Transport" , point: 1),
            CardGameModel(cardWord: "остановка", categoryName: "Transport" , point: 1),
            CardGameModel(cardWord: "проезд", categoryName: "Transport" , point: 1),
            CardGameModel(cardWord: "бензин", categoryName: "Transport" , point: 1),
            CardGameModel(cardWord: "общественный транспорт", categoryName: "Transport" , point: 1),
            CardGameModel(cardWord: "передвижение", categoryName: "Transport" , point: 1),
            CardGameModel(cardWord: "ехать", categoryName: "Transport" , point: 1),
            CardGameModel(cardWord: "путешествие", categoryName: "Transport" , point: 1),
            CardGameModel(cardWord: "трактор", categoryName: "Transport" , point: 1),
            CardGameModel(cardWord: "путь", categoryName: "Transport" , point: 1),
            CardGameModel(cardWord: "пробки", categoryName: "Transport" , point: 1),
            CardGameModel(cardWord: "движение", categoryName: "Transport" , point: 1),
            CardGameModel(cardWord: "грузовик", categoryName: "Transport" , point: 1),
            CardGameModel(cardWord: "пароход", categoryName: "Transport" , point: 1),
            CardGameModel(cardWord: "деньги", categoryName: "Transport" , point: 1),
            CardGameModel(cardWord: "лодка", categoryName: "Transport" , point: 1),
            CardGameModel(cardWord: "самокат", categoryName: "Transport" , point: 1),
            CardGameModel(cardWord: "двигатель", categoryName: "Transport" , point: 1),
            CardGameModel(cardWord: "скорость", categoryName: "Transport" , point: 1),
            CardGameModel(cardWord: "маршрут", categoryName: "Transport" , point: 1),
            CardGameModel(cardWord: "поездка", categoryName: "Transport" , point: 1),
            CardGameModel(cardWord: "светофор", categoryName: "Transport" , point: 1),
            CardGameModel(cardWord: "аэропорт", categoryName: "Transport" , point: 1),
            CardGameModel(cardWord: "ролики", categoryName: "Transport" , point: 1),
            CardGameModel(cardWord: "газель", categoryName: "Transport" , point: 1),
            CardGameModel(cardWord: "трасса", categoryName: "Transport" , point: 1),
            CardGameModel(cardWord: "работа", categoryName: "Transport" , point: 1),
            CardGameModel(cardWord: "окно", categoryName: "Transport" , point: 1),
            CardGameModel(cardWord: "транспортировка", categoryName: "Transport" , point: 1),
            CardGameModel(cardWord: "рельсы", categoryName: "Transport" , point: 1),
            CardGameModel(cardWord: "лошадь", categoryName: "Transport" , point: 1),
            CardGameModel(cardWord: "мопед", categoryName: "Transport" , point: 1),
            CardGameModel(cardWord: "сиденье", categoryName: "Transport" , point: 1),
            CardGameModel(cardWord: "перевозка", categoryName: "Transport" , point: 1),
            CardGameModel(cardWord: "место", categoryName: "Transport" , point: 1),
            CardGameModel(cardWord: "толпа", categoryName: "Transport" , point: 1),
            CardGameModel(cardWord: "права", categoryName: "Transport" , point: 1),
            CardGameModel(cardWord: "вокзал", categoryName: "Transport" , point: 1),
            CardGameModel(cardWord: "спорт", categoryName: "Transport" , point: 1),
            CardGameModel(cardWord: "шоссе", categoryName: "Transport" , point: 1),
            CardGameModel(cardWord: "проездной", categoryName: "Transport" , point: 1),
            CardGameModel(cardWord: "шофёр", categoryName: "Transport" , point: 1),
            CardGameModel(cardWord: "пешеход", categoryName: "Transport" , point: 1),
            CardGameModel(cardWord: "авария", categoryName: "Transport" , point: 1),
            CardGameModel(cardWord: "время", categoryName: "Transport" , point: 1),
            CardGameModel(cardWord: "катер", categoryName: "Transport" , point: 1),
            CardGameModel(cardWord: "оплата", categoryName: "Transport" , point: 1),
            CardGameModel(cardWord: "скутер", categoryName: "Transport" , point: 1),
            CardGameModel(cardWord: "человек", categoryName: "Transport" , point: 1),
            CardGameModel(cardWord: "техника", categoryName: "Transport" , point: 1),
            CardGameModel(cardWord: "транс", categoryName: "Transport" , point: 1),
            CardGameModel(cardWord: "топливо", categoryName: "Transport" , point: 1),
            CardGameModel(cardWord: "газ", categoryName: "Transport" , point: 1),
            CardGameModel(cardWord: "наземный", categoryName: "Transport" , point: 1),
            CardGameModel(cardWord: "передвигаться", categoryName: "Transport" , point: 1),
            CardGameModel(cardWord: "педали", categoryName: "Transport" , point: 1),
            CardGameModel(cardWord: "перемещение", categoryName: "Transport" , point: 1),
            CardGameModel(cardWord: "контролёр", categoryName: "Transport" , point: 1),
            CardGameModel(cardWord: "машинист", categoryName: "Transport" , point: 1),
            CardGameModel(cardWord: "общество", categoryName: "Transport" , point: 1),
            CardGameModel(cardWord: "ракета", categoryName: "Transport" , point: 1),
            CardGameModel(cardWord: "аэроплан", categoryName: "Transport" , point: 1),
            CardGameModel(cardWord: "воздушный транспорт", categoryName: "Transport" , point: 1),
            CardGameModel(cardWord: "личный", categoryName: "Transport" , point: 1),
            CardGameModel(cardWord: "пилот", categoryName: "Transport" , point: 1),
            CardGameModel(cardWord: "порт", categoryName: "Transport" , point: 1),
            CardGameModel(cardWord: "сидения", categoryName: "Transport" , point: 1),
            CardGameModel(cardWord: "личный транспорт", categoryName: "Transport" , point: 1),
            CardGameModel(cardWord: "транспортёр", categoryName: "Transport" , point: 1),
            CardGameModel(cardWord: "паровоз", categoryName: "Transport" , point: 1),
            CardGameModel(cardWord: "средство", categoryName: "Transport" , point: 1),
            CardGameModel(cardWord: "город", categoryName: "Transport" , point: 1),
            CardGameModel(cardWord: "танк", categoryName: "Transport" , point: 1),
            CardGameModel(cardWord: "водный", categoryName: "Transport" , point: 1),
            CardGameModel(cardWord: "бронетранспортёр", categoryName: "Transport" , point: 1),
            CardGameModel(cardWord: "трамвайчик", categoryName: "Transport" , point: 1),
            CardGameModel(cardWord: "автомобили", categoryName: "Transport" , point: 1),
            CardGameModel(cardWord: "транспортир", categoryName: "Transport" , point: 1),
            CardGameModel(cardWord: "вездеход", categoryName: "Transport" , point: 1),
            CardGameModel(cardWord: "билетик", categoryName: "Transport" , point: 1),
            CardGameModel(cardWord: "выезд", categoryName: "Transport" , point: 1),
            CardGameModel(cardWord: "экскаватор", categoryName: "Transport" , point: 1),
            CardGameModel(cardWord: "самоходка", categoryName: "Transport" , point: 1),
            CardGameModel(cardWord: "обоз", categoryName: "Transport" , point: 1),
            CardGameModel(cardWord: "тряска", categoryName: "Transport" , point: 1),
            CardGameModel(cardWord: "трансцендентность", categoryName: "Transport" , point: 1),
            CardGameModel(cardWord: "передок", categoryName: "Transport" , point: 1),
            CardGameModel(cardWord: "пассажиры", categoryName: "Transport" , point: 1),
            CardGameModel(cardWord: "ожидать", categoryName: "Transport" , point: 1),
            CardGameModel(cardWord: "наезд", categoryName: "Transport" , point: 1),
            CardGameModel(cardWord: "безбилетник", categoryName: "Transport" , point: 1),
            CardGameModel(cardWord: "бульдозер", categoryName: "Transport" , point: 1),
            CardGameModel(cardWord: "встречный", categoryName: "Transport" , point: 1),
            CardGameModel(cardWord: "кондукторша", categoryName: "Transport" , point: 1),
            CardGameModel(cardWord: "движения", categoryName: "Transport" , point: 1),
            CardGameModel(cardWord: "стоянка", categoryName: "Transport" , point: 1),
            CardGameModel(cardWord: "дороги", categoryName: "Transport" , point: 1),
            CardGameModel(cardWord: "кататься", categoryName: "Transport" , point: 1),
            CardGameModel(cardWord: "поезда", categoryName: "Transport" , point: 1),
            CardGameModel(cardWord: "колеса", categoryName: "Transport" , point: 1),
            CardGameModel(cardWord: "общий", categoryName: "Transport" , point: 1),
            CardGameModel(cardWord: "отъезд", categoryName: "Transport" , point: 1),
            CardGameModel(cardWord: "кибитка", categoryName: "Transport" , point: 1),
            CardGameModel(cardWord: "автобаза", categoryName: "Transport" , point: 1),
            CardGameModel(cardWord: "въезд", categoryName: "Transport" , point: 1),
            CardGameModel(cardWord: "приезд", categoryName: "Transport" , point: 1),
            CardGameModel(cardWord: "путешествовать", categoryName: "Transport" , point: 1),
            CardGameModel(cardWord: "станция", categoryName: "Transport" , point: 1),
            CardGameModel(cardWord: "автомашина", categoryName: "Transport" , point: 1),
            CardGameModel(cardWord: "машины", categoryName: "Transport" , point: 1),
            CardGameModel(cardWord: "прибытие", categoryName: "Transport" , point: 1),
            CardGameModel(cardWord: "автомобилист", categoryName: "Transport" , point: 1),
            CardGameModel(cardWord: "разъезд", categoryName: "Transport" , point: 1),
            CardGameModel(cardWord: "регулирование", categoryName: "Transport" , point: 1),
            CardGameModel(cardWord: "колесико", categoryName: "Transport" , point: 1),
            CardGameModel(cardWord: "экипаж", categoryName: "Transport" , point: 1),
            CardGameModel(cardWord: "водить", categoryName: "Transport" , point: 1),
            CardGameModel(cardWord: "двигаться", categoryName: "Transport" , point: 1),
            CardGameModel(cardWord: "драндулет", categoryName: "Transport" , point: 1),
            CardGameModel(cardWord: "машинка", categoryName: "Transport" , point: 1),
            CardGameModel(cardWord: "экспорт", categoryName: "Transport" , point: 1),
            CardGameModel(cardWord: "пешеходы", categoryName: "Transport" , point: 1),
            CardGameModel(cardWord: "велосипедист", categoryName: "Transport" , point: 1),
            CardGameModel(cardWord: "обслуживать", categoryName: "Transport" , point: 1),
            CardGameModel(cardWord: "улица", categoryName: "Transport" , point: 1),
            CardGameModel(cardWord: "ГАИ", categoryName: "Transport" , point: 1),
            CardGameModel(cardWord: "танки", categoryName: "Transport" , point: 1),
            CardGameModel(cardWord: "кабина", categoryName: "Transport" , point: 1),
            CardGameModel(cardWord: "теснота", categoryName: "Transport" , point: 1),
            CardGameModel(cardWord: "поставщики", categoryName: "Transport" , point: 1),
            CardGameModel(cardWord: "бричка", categoryName: "Transport" , point: 1),
            CardGameModel(cardWord: "эритроцит", categoryName: "Transport" , point: 1),
            CardGameModel(cardWord: "лошади", categoryName: "Transport" , point: 1),
            CardGameModel(cardWord: "отправление", categoryName: "Transport" , point: 1),
            
            CardGameModel(cardWord: "звёзды", categoryName: "Space" , point: 1),
            CardGameModel(cardWord: "ракета", categoryName: "Space" , point: 1),
            CardGameModel(cardWord: "космонавт", categoryName: "Space" , point: 1),
            CardGameModel(cardWord: "планеты", categoryName: "Space" , point: 1),
            CardGameModel(cardWord: "земля", categoryName: "Space" , point: 1),
            CardGameModel(cardWord: "планета", categoryName: "Space" , point: 1),
            CardGameModel(cardWord: "луна", categoryName: "Space" , point: 1),
            CardGameModel(cardWord: "солнце", categoryName: "Space" , point: 1),
            CardGameModel(cardWord: "Марс", categoryName: "Space" , point: 1),
            CardGameModel(cardWord: "небо", categoryName: "Space" , point: 1),
            CardGameModel(cardWord: "Гагарин", categoryName: "Space" , point: 1),
            CardGameModel(cardWord: "галактика", categoryName: "Space" , point: 1),
            CardGameModel(cardWord: "полёт", categoryName: "Space" , point: 1),
            CardGameModel(cardWord: "спутник", categoryName: "Space" , point: 1),
            CardGameModel(cardWord: "комета", categoryName: "Space" , point: 1),
            CardGameModel(cardWord: "вселенная", categoryName: "Space" , point: 1),
            CardGameModel(cardWord: "Юпитер", categoryName: "Space" , point: 1),
            CardGameModel(cardWord: "Венера", categoryName: "Space" , point: 1),
            CardGameModel(cardWord: "Сатурн", categoryName: "Space" , point: 1),
            CardGameModel(cardWord: "невесомость", categoryName: "Space" , point: 1),
            CardGameModel(cardWord: "метеорит", categoryName: "Space" , point: 1),
            CardGameModel(cardWord: "астероид", categoryName: "Space" , point: 1),
            CardGameModel(cardWord: "бесконечность", categoryName: "Space" , point: 1),
            CardGameModel(cardWord: "Нептун", categoryName: "Space" , point: 1),
            CardGameModel(cardWord: "Плутон", categoryName: "Space" , point: 1),
            CardGameModel(cardWord: "вакуум", categoryName: "Space" , point: 1),
            CardGameModel(cardWord: "созвездие", categoryName: "Space" , point: 1),
            CardGameModel(cardWord: "орбита", categoryName: "Space" , point: 1),
            CardGameModel(cardWord: "млечный путь", categoryName: "Space" , point: 1),
            CardGameModel(cardWord: "корабль", categoryName: "Space" , point: 1),
            CardGameModel(cardWord: "пространство", categoryName: "Space" , point: 1),
            CardGameModel(cardWord: "Меркурий", categoryName: "Space" , point: 1),
            CardGameModel(cardWord: "скафандр", categoryName: "Space" , point: 1),
            CardGameModel(cardWord: "инопланетяне", categoryName: "Space" , point: 1),
            CardGameModel(cardWord: "гравитация", categoryName: "Space" , point: 1),
            CardGameModel(cardWord: "чёрная дыра", categoryName: "Space" , point: 1),
            CardGameModel(cardWord: "солнечная система", categoryName: "Space" , point: 1),
            CardGameModel(cardWord: "уран", categoryName: "Space" , point: 1),
            CardGameModel(cardWord: "дыра", categoryName: "Space" , point: 1),
            CardGameModel(cardWord: "атмосфера", categoryName: "Space" , point: 1),
            CardGameModel(cardWord: "темнота", categoryName: "Space" , point: 1),
            CardGameModel(cardWord: "астронавт", categoryName: "Space" , point: 1),
            CardGameModel(cardWord: "станция", categoryName: "Space" , point: 1),
            CardGameModel(cardWord: "мир", categoryName: "Space" , point: 1),
            CardGameModel(cardWord: "астрономия", categoryName: "Space" , point: 1),
            CardGameModel(cardWord: "ночь", categoryName: "Space" , point: 1),
            CardGameModel(cardWord: "космический корабль", categoryName: "Space" , point: 1),
            CardGameModel(cardWord: "космический", categoryName: "Space" , point: 1),
            CardGameModel(cardWord: "телескоп", categoryName: "Space" , point: 1),
            CardGameModel(cardWord: "воздух", categoryName: "Space" , point: 1),
            CardGameModel(cardWord: "красота", categoryName: "Space" , point: 1),
            CardGameModel(cardWord: "путь", categoryName: "Space" , point: 1),
            CardGameModel(cardWord: "темно", categoryName: "Space" , point: 1),
            CardGameModel(cardWord: "шаттл", categoryName: "Space" , point: 1),
            CardGameModel(cardWord: "метеор", categoryName: "Space" , point: 1),
            CardGameModel(cardWord: "астроном", categoryName: "Space" , point: 1),
            CardGameModel(cardWord: "наука", categoryName: "Space" , point: 1),
            CardGameModel(cardWord: "свет", categoryName: "Space" , point: 1),
            CardGameModel(cardWord: "пустота", categoryName: "Space" , point: 1),
            CardGameModel(cardWord: "человек", categoryName: "Space" , point: 1),
            CardGameModel(cardWord: "система", categoryName: "Space" , point: 1),
            CardGameModel(cardWord: "холод", categoryName: "Space" , point: 1),
            CardGameModel(cardWord: "вечность", categoryName: "Space" , point: 1),
            CardGameModel(cardWord: "тьма", categoryName: "Space" , point: 1),
            CardGameModel(cardWord: "физика", categoryName: "Space" , point: 1),
            CardGameModel(cardWord: "далёко", categoryName: "Space" , point: 1),
            CardGameModel(cardWord: "стрелка", categoryName: "Space" , point: 1),
            CardGameModel(cardWord: "летать", categoryName: "Space" , point: 1),
            CardGameModel(cardWord: "жизнь", categoryName: "Space" , point: 1),
            CardGameModel(cardWord: "Байконур", categoryName: "Space" , point: 1),
            CardGameModel(cardWord: "большая медведица", categoryName: "Space" , point: 1),
            CardGameModel(cardWord: "мусор", categoryName: "Space" , point: 1),
            CardGameModel(cardWord: "НЛО", categoryName: "Space" , point: 1),
            CardGameModel(cardWord: "МКС", categoryName: "Space" , point: 1),
            CardGameModel(cardWord: "космодром", categoryName: "Space" , point: 1),
            CardGameModel(cardWord: "космонавтика", categoryName: "Space" , point: 1),
            CardGameModel(cardWord: "притяжение", categoryName: "Space" , point: 1),
            CardGameModel(cardWord: "мечта", categoryName: "Space" , point: 1),
            CardGameModel(cardWord: "чернота", categoryName: "Space" , point: 1),
            CardGameModel(cardWord: "астрология", categoryName: "Space" , point: 1),
            CardGameModel(cardWord: "белка", categoryName: "Space" , point: 1),
            CardGameModel(cardWord: "звездопад", categoryName: "Space" , point: 1),
            CardGameModel(cardWord: "союз", categoryName: "Space" , point: 1),
            CardGameModel(cardWord: "неизвестность", categoryName: "Space" , point: 1),
            CardGameModel(cardWord: "время", categoryName: "Space" , point: 1),
            CardGameModel(cardWord: "пыль", categoryName: "Space" , point: 1),
            CardGameModel(cardWord: "самолёт", categoryName: "Space" , point: 1),
            CardGameModel(cardWord: "Андромеда", categoryName: "Space" , point: 1),
            CardGameModel(cardWord: "Орион", categoryName: "Space" , point: 1),
            CardGameModel(cardWord: "Юрий", categoryName: "Space" , point: 1),
            CardGameModel(cardWord: "марсоход", categoryName: "Space" , point: 1),
            CardGameModel(cardWord: "млечный", categoryName: "Space" , point: 1),
            CardGameModel(cardWord: "космический мусор", categoryName: "Space" , point: 1),
            CardGameModel(cardWord: "пришельцы", categoryName: "Space" , point: 1),
            CardGameModel(cardWord: "марсианин", categoryName: "Space" , point: 1),
            CardGameModel(cardWord: "луноход", categoryName: "Space" , point: 1),
            CardGameModel(cardWord: "высоко", categoryName: "Space" , point: 1),
            CardGameModel(cardWord: "кислород", categoryName: "Space" , point: 1),
            CardGameModel(cardWord: "апрель", categoryName: "Space" , point: 1),
            CardGameModel(cardWord: "заезды", categoryName: "Space" , point: 1),
            CardGameModel(cardWord: "космиеский корабль", categoryName: "Space" , point: 1),
            CardGameModel(cardWord: "космонавты", categoryName: "Space" , point: 1),
            CardGameModel(cardWord: "космопорт", categoryName: "Space" , point: 1),
            CardGameModel(cardWord: "марс (планета)", categoryName: "Space" , point: 1),
            CardGameModel(cardWord: "метеориты", categoryName: "Space" , point: 1),
            CardGameModel(cardWord: "орбитальная станция", categoryName: "Space" , point: 1),
            CardGameModel(cardWord: "парад планет", categoryName: "Space" , point: 1),
            CardGameModel(cardWord: "стратосфера", categoryName: "Space" , point: 1),
            CardGameModel(cardWord: "Юрий Гагарин", categoryName: "Space" , point: 1),
            CardGameModel(cardWord: "планета земля", categoryName: "Space" , point: 1),
            CardGameModel(cardWord: "космические войска", categoryName: "Space" , point: 1),
            CardGameModel(cardWord: "звезда", categoryName: "Space" , point: 1),
            CardGameModel(cardWord: "марсиане", categoryName: "Space" , point: 1),
            CardGameModel(cardWord: "инопланетянин", categoryName: "Space" , point: 1),
            CardGameModel(cardWord: "пришелец", categoryName: "Space" , point: 1),
            CardGameModel(cardWord: "обсерватория", categoryName: "Space" , point: 1),
            CardGameModel(cardWord: "ракетодром", categoryName: "Space" , point: 1),
            CardGameModel(cardWord: "луны", categoryName: "Space" , point: 1),
            CardGameModel(cardWord: "нло (неопознанный летающий объект)", categoryName: "Space" , point: 1),
            CardGameModel(cardWord: "стыковка", categoryName: "Space" , point: 1),
            CardGameModel(cardWord: "капсула", categoryName: "Space" , point: 1),
            CardGameModel(cardWord: "землянин", categoryName: "Space" , point: 1),
            CardGameModel(cardWord: "научная фантастика", categoryName: "Space" , point: 1),
            CardGameModel(cardWord: "затмение", categoryName: "Space" , point: 1),
            CardGameModel(cardWord: "пуск", categoryName: "Space" , point: 1),
            CardGameModel(cardWord: "арбитр", categoryName: "Space" , point: 1),
            CardGameModel(cardWord: "мироздание", categoryName: "Space" , point: 1),
            CardGameModel(cardWord: "ракетка", categoryName: "Space" , point: 1),
            CardGameModel(cardWord: "звёздочка", categoryName: "Space" , point: 1),
            CardGameModel(cardWord: "гало", categoryName: "Space" , point: 1),
            CardGameModel(cardWord: "фантастика", categoryName: "Space" , point: 1),
            CardGameModel(cardWord: "запускать", categoryName: "Space" , point: 1),
            CardGameModel(cardWord: "сфера", categoryName: "Space" , point: 1),
            CardGameModel(cardWord: "освоение", categoryName: "Space" , point: 1),
            CardGameModel(cardWord: "лунная", categoryName: "Space" , point: 1),
            CardGameModel(cardWord: "сквозь", categoryName: "Space" , point: 1),
            CardGameModel(cardWord: "небеса", categoryName: "Space" , point: 1),
            CardGameModel(cardWord: "будущее", categoryName: "Space" , point: 1),
            CardGameModel(cardWord: "полушарие", categoryName: "Space" , point: 1),
            CardGameModel(cardWord: "зонд", categoryName: "Space" , point: 1),
            CardGameModel(cardWord: "футурама", categoryName: "Space" , point: 1),
            CardGameModel(cardWord: "красоты", categoryName: "Space" , point: 1),
            CardGameModel(cardWord: "давление", categoryName: "Space" , point: 1),
            CardGameModel(cardWord: "небосвод", categoryName: "Space" , point: 1),
            CardGameModel(cardWord: "тяготение", categoryName: "Space" , point: 1),
            CardGameModel(cardWord: "авиаконструктор", categoryName: "Space" , point: 1),
            CardGameModel(cardWord: "летающий", categoryName: "Space" , point: 1),
            CardGameModel(cardWord: "тюбик", categoryName: "Space" , point: 1),
            CardGameModel(cardWord: "простор", categoryName: "Space" , point: 1),
            CardGameModel(cardWord: "измерение", categoryName: "Space" , point: 1),
            CardGameModel(cardWord: "целая вечность", categoryName: "Space" , point: 1),
            CardGameModel(cardWord: "портал", categoryName: "Space" , point: 1),
            CardGameModel(cardWord: "лазер", categoryName: "Space" , point: 1),
            CardGameModel(cardWord: "исследование", categoryName: "Space" , point: 1),
            CardGameModel(cardWord: "антенна", categoryName: "Space" , point: 1),
            CardGameModel(cardWord: "комсомолец", categoryName: "Space" , point: 1),
            CardGameModel(cardWord: "цивилизация", categoryName: "Space" , point: 1),
            CardGameModel(cardWord: "неизвестное", categoryName: "Space" , point: 1),
            CardGameModel(cardWord: "дырки", categoryName: "Space" , point: 1),
            CardGameModel(cardWord: "тишина", categoryName: "Space" , point: 1),
            
            CardGameModel(cardWord: "самолёт", categoryName: "Travel", point: 1),
            CardGameModel(cardWord: "море", categoryName: "Travel", point: 1),
            CardGameModel(cardWord: "отдых", categoryName: "Travel", point: 1),
            CardGameModel(cardWord: "поезд", categoryName: "Travel", point: 1),
            CardGameModel(cardWord: "дорога", categoryName: "Travel", point: 1),
            CardGameModel(cardWord: "отпуск", categoryName: "Travel", point: 1),
            CardGameModel(cardWord: "путь", categoryName: "Travel", point: 1),
            CardGameModel(cardWord: "страна", categoryName: "Travel", point: 1),
            CardGameModel(cardWord: "машина", categoryName: "Travel", point: 1),
            CardGameModel(cardWord: "путешественник", categoryName: "Travel", point: 1),
            CardGameModel(cardWord: "поездка", categoryName: "Travel", point: 1),
            CardGameModel(cardWord: "пляж", categoryName: "Travel", point: 1),
            CardGameModel(cardWord: "горы", categoryName: "Travel", point: 1),
            CardGameModel(cardWord: "турист", categoryName: "Travel", point: 1),
            CardGameModel(cardWord: "чемодан", categoryName: "Travel", point: 1),
            CardGameModel(cardWord: "поход", categoryName: "Travel", point: 1),
            CardGameModel(cardWord: "круиз", categoryName: "Travel", point: 1),
            CardGameModel(cardWord: "рюкзак", categoryName: "Travel", point: 1),
            CardGameModel(cardWord: "мир", categoryName: "Travel", point: 1),
            CardGameModel(cardWord: "приключение", categoryName: "Travel", point: 1),
            CardGameModel(cardWord: "билет", categoryName: "Travel", point: 1),
            CardGameModel(cardWord: "город", categoryName: "Travel", point: 1),
            CardGameModel(cardWord: "солнце", categoryName: "Travel", point: 1),
            CardGameModel(cardWord: "туризм", categoryName: "Travel", point: 1),
            CardGameModel(cardWord: "полёт", categoryName: "Travel", point: 1),
            CardGameModel(cardWord: "радость", categoryName: "Travel", point: 1),
            CardGameModel(cardWord: "отель", categoryName: "Travel", point: 1),
            CardGameModel(cardWord: "палатка", categoryName: "Travel", point: 1),
            CardGameModel(cardWord: "автобус", categoryName: "Travel", point: 1),
            CardGameModel(cardWord: "автостоп", categoryName: "Travel", point: 1),
            CardGameModel(cardWord: "деньги", categoryName: "Travel", point: 1),
            CardGameModel(cardWord: "тур", categoryName: "Travel", point: 1),
            CardGameModel(cardWord: "карта", categoryName: "Travel", point: 1),
            CardGameModel(cardWord: "лето", categoryName: "Travel", point: 1),
            CardGameModel(cardWord: "Турция", categoryName: "Travel", point: 1),
            CardGameModel(cardWord: "корабль", categoryName: "Travel", point: 1),
            CardGameModel(cardWord: "экскурсия", categoryName: "Travel", point: 1),
            CardGameModel(cardWord: "путешествовать", categoryName: "Travel", point: 1),
            CardGameModel(cardWord: "люди", categoryName: "Travel", point: 1),
            CardGameModel(cardWord: "курорт", categoryName: "Travel", point: 1),
            CardGameModel(cardWord: "вояж", categoryName: "Travel", point: 1),
            CardGameModel(cardWord: "багаж", categoryName: "Travel", point: 1),
            CardGameModel(cardWord: "путёвка", categoryName: "Travel", point: 1),
            CardGameModel(cardWord: "друзья", categoryName: "Travel", point: 1),
            CardGameModel(cardWord: "костёр", categoryName: "Travel", point: 1),
            CardGameModel(cardWord: "Египет", categoryName: "Travel", point: 1),
            CardGameModel(cardWord: "лес", categoryName: "Travel", point: 1),
            CardGameModel(cardWord: "семья", categoryName: "Travel", point: 1),
            CardGameModel(cardWord: "океан", categoryName: "Travel", point: 1),
            CardGameModel(cardWord: "остров", categoryName: "Travel", point: 1),
            CardGameModel(cardWord: "интерес", categoryName: "Travel", point: 1),
            CardGameModel(cardWord: "счастье", categoryName: "Travel", point: 1),
            CardGameModel(cardWord: "кругосветное путешествие", categoryName: "Travel", point: 1),
            CardGameModel(cardWord: "шествие", categoryName: "Travel", point: 1),
            CardGameModel(cardWord: "песок", categoryName: "Travel", point: 1),
            CardGameModel(cardWord: "еда", categoryName: "Travel", point: 1),
            CardGameModel(cardWord: "земля", categoryName: "Travel", point: 1),
            CardGameModel(cardWord: "любовь", categoryName: "Travel", point: 1),
            CardGameModel(cardWord: "трип", categoryName: "Travel", point: 1),
            CardGameModel(cardWord: "шар", categoryName: "Travel", point: 1),
            CardGameModel(cardWord: "кругосветное", categoryName: "Travel", point: 1),
            CardGameModel(cardWord: "путник", categoryName: "Travel", point: 1),
            CardGameModel(cardWord: "ехать", categoryName: "Travel", point: 1),
            CardGameModel(cardWord: "заграница", categoryName: "Travel", point: 1),
            CardGameModel(cardWord: "время", categoryName: "Travel", point: 1),
            CardGameModel(cardWord: "природа", categoryName: "Travel", point: 1),
            CardGameModel(cardWord: "веселье", categoryName: "Travel", point: 1),
            CardGameModel(cardWord: "вода", categoryName: "Travel", point: 1),
            CardGameModel(cardWord: "впечатления", categoryName: "Travel", point: 1),
            CardGameModel(cardWord: "гид", categoryName: "Travel", point: 1),
            CardGameModel(cardWord: "странствие", categoryName: "Travel", point: 1),
            CardGameModel(cardWord: "маршрут", categoryName: "Travel", point: 1),
            CardGameModel(cardWord: "каникулы", categoryName: "Travel", point: 1),
            CardGameModel(cardWord: "перелёт", categoryName: "Travel", point: 1),
            CardGameModel(cardWord: "пальма", categoryName: "Travel", point: 1),
            CardGameModel(cardWord: "фотографии", categoryName: "Travel", point: 1),
            CardGameModel(cardWord: "человек", categoryName: "Travel", point: 1),
            CardGameModel(cardWord: "сумка", categoryName: "Travel", point: 1),
            CardGameModel(cardWord: "паспорт", categoryName: "Travel", point: 1),
            CardGameModel(cardWord: "транспорт", categoryName: "Travel", point: 1),
            CardGameModel(cardWord: "вокруг света", categoryName: "Travel", point: 1),
            CardGameModel(cardWord: "достопримечательности", categoryName: "Travel", point: 1),
            CardGameModel(cardWord: "небо", categoryName: "Travel", point: 1),
            CardGameModel(cardWord: "свет", categoryName: "Travel", point: 1),
            CardGameModel(cardWord: "новое", categoryName: "Travel", point: 1),
            CardGameModel(cardWord: "виза", categoryName: "Travel", point: 1),
            CardGameModel(cardWord: "путеводитель", categoryName: "Travel", point: 1),
            CardGameModel(cardWord: "компас", categoryName: "Travel", point: 1),
            CardGameModel(cardWord: "сувениры", categoryName: "Travel", point: 1),
            CardGameModel(cardWord: "гостиница", categoryName: "Travel", point: 1),
            CardGameModel(cardWord: "аэропорт", categoryName: "Travel", point: 1),
            CardGameModel(cardWord: "лодка", categoryName: "Travel", point: 1),
            CardGameModel(cardWord: "велосипед", categoryName: "Travel", point: 1),
            CardGameModel(cardWord: "автомобиль", categoryName: "Travel", point: 1),
            CardGameModel(cardWord: "фото", categoryName: "Travel", point: 1),
            CardGameModel(cardWord: "озеро", categoryName: "Travel", point: 1),
            CardGameModel(cardWord: "Америка", categoryName: "Travel", point: 1),
            CardGameModel(cardWord: "Европа", categoryName: "Travel", point: 1),
            CardGameModel(cardWord: "вещи", categoryName: "Travel", point: 1),
            CardGameModel(cardWord: "далёко", categoryName: "Travel", point: 1),
            CardGameModel(cardWord: "приключения", categoryName: "Travel", point: 1),
            CardGameModel(cardWord: "туристы", categoryName: "Travel", point: 1),
            CardGameModel(cardWord: "скитание", categoryName: "Travel", point: 1),
            CardGameModel(cardWord: "турпоездка", categoryName: "Travel", point: 1),
            CardGameModel(cardWord: "страны", categoryName: "Travel", point: 1),
            CardGameModel(cardWord: "саквояж", categoryName: "Travel", point: 1),
            CardGameModel(cardWord: "одиссея", categoryName: "Travel", point: 1),
            CardGameModel(cardWord: "длинное", categoryName: "Travel", point: 1),
            CardGameModel(cardWord: "интурист", categoryName: "Travel", point: 1),
            CardGameModel(cardWord: "кочевник", categoryName: "Travel", point: 1),
            CardGameModel(cardWord: "авиабилет", categoryName: "Travel", point: 1),
            CardGameModel(cardWord: "отъезд", categoryName: "Travel", point: 1),
            CardGameModel(cardWord: "следование", categoryName: "Travel", point: 1),
            CardGameModel(cardWord: "иммигрант", categoryName: "Travel", point: 1),
            CardGameModel(cardWord: "решка", categoryName: "Travel", point: 1),
            CardGameModel(cardWord: "прошествие", categoryName: "Travel", point: 1),
            CardGameModel(cardWord: "иностранцы", categoryName: "Travel", point: 1),
            CardGameModel(cardWord: "достопримечательность", categoryName: "Travel", point: 1),
            CardGameModel(cardWord: "теплоход", categoryName: "Travel", point: 1),
            CardGameModel(cardWord: "гастроль", categoryName: "Travel", point: 1),
            CardGameModel(cardWord: "корабли", categoryName: "Travel", point: 1),
            CardGameModel(cardWord: "сувенир", categoryName: "Travel", point: 1),
            CardGameModel(cardWord: "чемоданчик", categoryName: "Travel", point: 1),
            CardGameModel(cardWord: "телепорт", categoryName: "Travel", point: 1),
            CardGameModel(cardWord: "приезд", categoryName: "Travel", point: 1),
            CardGameModel(cardWord: "сафари", categoryName: "Travel", point: 1),
            CardGameModel(cardWord: "дирижабль", categoryName: "Travel", point: 1),
            CardGameModel(cardWord: "гулливер", categoryName: "Travel", point: 1),
            CardGameModel(cardWord: "возвращение", categoryName: "Travel", point: 1),
            CardGameModel(cardWord: "география", categoryName: "Travel", point: 1),
            CardGameModel(cardWord: "космиеский корабль", categoryName: "Travel", point: 1),
            CardGameModel(cardWord: "кордон", categoryName: "Travel", point: 1),
            CardGameModel(cardWord: "пилигрим", categoryName: "Travel", point: 1),
            CardGameModel(cardWord: "дороги", categoryName: "Travel", point: 1),
            CardGameModel(cardWord: "поезда", categoryName: "Travel", point: 1),
            CardGameModel(cardWord: "пассажир", categoryName: "Travel", point: 1),
            CardGameModel(cardWord: "вылазка", categoryName: "Travel", point: 1),
            CardGameModel(cardWord: "каравелла", categoryName: "Travel", point: 1),
            CardGameModel(cardWord: "управлять", categoryName: "Travel", point: 1),
            CardGameModel(cardWord: "передвижение", categoryName: "Travel", point: 1),
            CardGameModel(cardWord: "лайнер", categoryName: "Travel", point: 1),
            CardGameModel(cardWord: "загранпаспорт", categoryName: "Travel", point: 1),
            CardGameModel(cardWord: "даль", categoryName: "Travel", point: 1),
            CardGameModel(cardWord: "молодожён", categoryName: "Travel", point: 1),
            CardGameModel(cardWord: "города", categoryName: "Travel", point: 1),
            CardGameModel(cardWord: "мечта", categoryName: "Travel", point: 1),
            CardGameModel(cardWord: "плот", categoryName: "Travel", point: 1),
            CardGameModel(cardWord: "вагон", categoryName: "Travel", point: 1),
            CardGameModel(cardWord: "паруса", categoryName: "Travel", point: 1),
            CardGameModel(cardWord: "шпалы", categoryName: "Travel", point: 1),
            CardGameModel(cardWord: "направление", categoryName: "Travel", point: 1),
            CardGameModel(cardWord: "Бразилия", categoryName: "Travel", point: 1),
            CardGameModel(cardWord: "спутница", categoryName: "Travel", point: 1),
            CardGameModel(cardWord: "прибытие", categoryName: "Travel", point: 1),
            CardGameModel(cardWord: "граница", categoryName: "Travel", point: 1),
            CardGameModel(cardWord: "магнит", categoryName: "Travel", point: 1),
            CardGameModel(cardWord: "иностранец", categoryName: "Travel", point: 1),
            CardGameModel(cardWord: "проводница", categoryName: "Travel", point: 1),
            CardGameModel(cardWord: "Колобок", categoryName: "Travel", point: 1),
            CardGameModel(cardWord: "проводник", categoryName: "Travel", point: 1)
            ]
    }
}
